// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.6

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	conversationsFieldNames          = builder.RawFieldNames(&Conversations{})
	conversationsRows                = strings.Join(conversationsFieldNames, ",")
	conversationsRowsExpectAutoSet   = strings.Join(stringx.Remove(conversationsFieldNames), ",")
	conversationsRowsWithPlaceHolder = strings.Join(stringx.Remove(conversationsFieldNames, "`conversation_id`"), "=?,") + "=?"
)

type (
	conversationsModel interface {
		Insert(ctx context.Context, data *Conversations) (sql.Result, error)
		FindOne(ctx context.Context, conversationId int64) (*Conversations, error)
		Update(ctx context.Context, data *Conversations) error
		Delete(ctx context.Context, conversationId int64) error
	}

	defaultConversationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Conversations struct {
		ConversationId int64          `db:"conversation_id"`
		Name           sql.NullString `db:"name"`
		CreatedBy      int64          `db:"created_by"`
		CreatedAt      sql.NullInt64  `db:"created_at"`
	}
)

func newConversationsModel(conn sqlx.SqlConn) *defaultConversationsModel {
	return &defaultConversationsModel{
		conn:  conn,
		table: "`conversations`",
	}
}

func (m *defaultConversationsModel) Delete(ctx context.Context, conversationId int64) error {
	query := fmt.Sprintf("delete from %s where `conversation_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, conversationId)
	return err
}

func (m *defaultConversationsModel) FindOne(ctx context.Context, conversationId int64) (*Conversations, error) {
	query := fmt.Sprintf("select %s from %s where `conversation_id` = ? limit 1", conversationsRows, m.table)
	var resp Conversations
	err := m.conn.QueryRowCtx(ctx, &resp, query, conversationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationsModel) Insert(ctx context.Context, data *Conversations) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, conversationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.Name, data.CreatedBy, data.CreatedAt)
	return ret, err
}

func (m *defaultConversationsModel) Update(ctx context.Context, data *Conversations) error {
	query := fmt.Sprintf("update %s set %s where `conversation_id` = ?", m.table, conversationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.CreatedBy, data.CreatedAt, data.ConversationId)
	return err
}

func (m *defaultConversationsModel) tableName() string {
	return m.table
}
